services:
  - type: web
    name: exver-altura
    runtime: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: "public, max-age=60, must-revalidate"
      - path: "/*.css"
        name: Cache-Control
        value: "public, max-age=86400"
      - path: "/*.js"
        name: Cache-Control
        value: "public, max-age=86400"
